### ISSUE TITLE
Nav and logo colors don't match well

### ISSUE THREAD

**Issue by mahcloud** [RocketNanny/RocketNanny#30]
So, I made the logo using https://flatuicolors.com/ pumpkin pomegranate and midnight blue.
This doesn't seem to be matching well with the #000033 of the nav bar.

![image](https://cloud.githubusercontent.com/assets/1529103/14712056/e7b45f54-0798-11e6-872a-6b47e4888c3e.png)

@dooliddler do you have a preference on color?

**Comment by dooliddler** [comment]
Thanks.  I'll explore although at this point I don't want to bog you down with color schemes and logos at this point.

**Comment by mahcloud** [comment]
@dooliddler @huhwhatyah I have created a style tag on the issues that related to style. Let's ignore those for now, sound good?

**Comment by dooliddler** [comment]
Yes.
