### ISSUE TITLE
Add nav to homepage

### ISSUE THREAD

**Issue by mahcloud** [RocketNanny/RocketNanny#7]
Nav should have site title, logo and login/signup links

**Comment by mahcloud** [comment]
The homepage can be found at /web/static/js/react/pages/home-page.js. Any HTML added to the render function will show on the home page automatically.

**Comment by mahcloud** [comment]
We need a nav bar accross the top of the site. It can look like GitHub or Amazon or any of your favorite clean sites. @dooliddler is going for an MVP site, so any nav bar that is clean and simple should probably work.

**Comment by dooliddler** [comment]
I thing modeling after the Amazon mobile header (logo/name top left, sign in link with icon) would work.  Should swap the shopping cart for the menu icon.
